name: Unzip and Delete Uploaded Zip File

on:
  push:
    paths:
      - '*.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Unzip uploaded file
      run: |
        for file in *.zip; do
          unzip -o "$file" -d "./"
        done

    - name: Delete zip file
      run: |
        rm *.zip
