name: Unzip and Delete Uploaded Zip File

on:
  push:
    paths:
      - 'uploads/*.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Unzip uploaded file
      run: |
        for file in uploads/*.zip; do
          unzip -o "$file" -d "uploads/"
        done

    - name: Delete zip file
      run: |
        rm uploads/*.zip
