name: Unzip All Root Zip Files

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Unzip all zip files in root if present
      run: |
        shopt -s nullglob
        for file in *.zip; do
          echo "Unzipping $file"
          unzip -o "$file" -d "./"
        done

    - name: Delete zip file(s) in root if present
      run: |
        shopt -s nullglob
        for file in *.zip; do
          echo "Deleting $file"
          rm "$file"
        done
