name: Unzip and Delete Uploaded Zip File

on:
  push:
    paths:
      - 'uploads/*.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Wait for uploaded zip file
      run: |
        while [ ! -f uploads/*.zip ]; do
          echo "Waiting for zip file..."
          sleep 10
        done

    - name: Unzip uploaded file
      run: |
        for file in uploads/*.zip; do
          unzip -o "$file" -d "uploads/"
        done

    - name: Delete zip file
      run: |
        rm uploads/*.zip

    - name: Error handling
      if: failure()
      run: |
        echo "An error occurred during the unzip process."
        exit 1

    - name: Retry unzip step
      run: |
        for i in {1..3}; do
          if unzip -o "uploads/*.zip" -d "uploads/"; then
            break
          else
            echo "Retrying unzip step ($i/3)..."
            sleep 10
          fi
        done
